param(
  [Parameter(Mandatory = $true)][string]$PidPath,
  [Parameter(Mandatory = $true)][string]$OwnershipToken,
  [Parameter(Mandatory = $true)][string]$DxfOutputPath
)

$ErrorActionPreference='Stop';$DxfOutputPath=[IO.Path]::GetFullPath($DxfOutputPath)
if([IO.Path]::GetExtension($DxfOutputPath)-ine'.dxf'-or(Test-Path -LiteralPath $DxfOutputPath)){throw 'F-030 DXF output must be a new .dxf path.'}
$interopCommonPath='C:\Program Files\Autodesk\AutoCAD 2024\Autodesk.AutoCAD.Interop.Common.dll';if(-not(Test-Path -LiteralPath $interopCommonPath)){throw "F-030 requires $interopCommonPath"};Add-Type -Path $interopCommonPath
Add-Type @'
using System;
using System.Runtime.InteropServices;
public static class F030WindowProcess {
  [DllImport("user32.dll")]
  public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint processId);
}
'@
function Invoke-ComRetry{param([Parameter(Mandatory=$true)][scriptblock]$Action,[int]$TimeoutSeconds=20);$deadline=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);do{try{return (& $Action)}catch{if([DateTime]::UtcNow-ge$deadline){throw};Start-Sleep -Milliseconds 150}}while($true)}
function Invoke-NonNullCom{param([Parameter(Mandatory=$true)][scriptblock]$Action,[string]$Label,[int]$TimeoutSeconds=20);$deadline=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);do{try{$value=& $Action;if($null-ne$value){return $value}}catch{if([DateTime]::UtcNow-ge$deadline){throw}};if([DateTime]::UtcNow-ge$deadline){throw "$Label remained null."};Start-Sleep -Milliseconds 150}while($true)}
function Wait-AcadIdle{param($Document,[int]$TimeoutSeconds=45);$deadline=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 100;try{if([string]::IsNullOrWhiteSpace([string]$Document.GetVariable('CMDNAMES'))-and[int]$Document.GetVariable('CMDACTIVE')-eq0){return}}catch{}}while([DateTime]::UtcNow-lt$deadline);throw "F-030 AutoCAD did not return idle. CMDNAMES='$($Document.GetVariable('CMDNAMES'))' LASTPROMPT='$($Document.GetVariable('LASTPROMPT'))'"}
function Wait-AcadMarker{param($Document,[string]$Marker,[int]$TimeoutSeconds=45);$deadline=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);do{Start-Sleep -Milliseconds 100;try{if([string]$Document.GetVariable('USERS1')-eq$Marker){Wait-AcadIdle $Document $TimeoutSeconds;return}}catch{}}while([DateTime]::UtcNow-lt$deadline);throw "F-030 marker $Marker timed out. CMDNAMES='$($Document.GetVariable('CMDNAMES'))' LASTPROMPT='$($Document.GetVariable('LASTPROMPT'))'"}
function Get-StringSha256{param([string]$Value);$hash=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($hash.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()}}
function Get-FileSha256{param([string]$Path);$hash=[Security.Cryptography.SHA256]::Create();$stream=[IO.File]::OpenRead($Path);try{return([BitConverter]::ToString($hash.ComputeHash($stream)).Replace('-','').ToLowerInvariant())}finally{$stream.Dispose();$hash.Dispose()}}
function Get-OwnedAcadIdentity{param([int]$ProcessId);$process=Get-Process -Id $ProcessId -ErrorAction Stop;$path=[IO.Path]::GetFullPath([string]$process.Path);if([IO.Path]::GetFileName($path)-ine'acad.exe'){throw "F-030 PID $ProcessId is not acad.exe."};$start=$process.StartTime.ToUniversalTime().ToString('o');$version=(Get-Item -LiteralPath $path).VersionInfo;return [ordered]@{processId=$ProcessId;executablePath=$path;executableName='acad.exe';executableSha256=Get-FileSha256 $path;fileVersion=[string]$version.FileVersion;productVersion=[string]$version.ProductVersion;startTimeUtc=$start;startTimeSha256=Get-StringSha256 $start}}
function Write-OwnedPidSidecar{param([int]$ProcessId);$identity=Get-OwnedAcadIdentity $ProcessId;[ordered]@{schemaVersion=1;processId=$identity.processId;executablePath=$identity.executablePath;executableName=$identity.executableName;executableSha256=$identity.executableSha256;fileVersion=$identity.fileVersion;productVersion=$identity.productVersion;startTimeUtc=$identity.startTimeUtc;startTimeSha256=$identity.startTimeSha256;owned=$true;token=$OwnershipToken}|ConvertTo-Json -Compress|Set-Content -LiteralPath $PidPath -Encoding ascii;return $identity}
function Get-InstalledAutoCadUpdateIdentity{$items=@(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*' -ErrorAction SilentlyContinue)+@(Get-ItemProperty 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*' -ErrorAction SilentlyContinue);$match=$items|Where-Object{$_.DisplayName-eq'Autodesk AutoCAD 2024.1.2 Update'}|Select-Object -First 1;if($match){return [ordered]@{displayName=[string]$match.DisplayName;displayVersion=[string]$match.DisplayVersion}};return $null}
function Format-Number{param([double]$Value);return [string]::Format([Globalization.CultureInfo]::InvariantCulture,'{0:R}',$Value)}
function Format-Point{param([double]$X,[double]$Y);return "(list $(Format-Number $X) $(Format-Number $Y) 0.0)"}
function Get-Point2{param($Value);return @([double]$Value[0],[double]$Value[1])}
function Get-EntityState{
  param($Entity);$name=[string](Invoke-ComRetry{$Entity.ObjectName});$details=[ordered]@{}
  if($name-eq'AcDbLine'){$details.start=Get-Point2(Invoke-NonNullCom{$Entity.StartPoint}'line start');$details.end=Get-Point2(Invoke-NonNullCom{$Entity.EndPoint}'line end')}
  elseif($name-eq'AcDbCircle'){$details.center=Get-Point2(Invoke-NonNullCom{$Entity.Center}'circle center');$details.radius=[double](Invoke-ComRetry{$Entity.Radius})}
  elseif($name-eq'AcDbPolyline'){$flat=@(Invoke-NonNullCom{$Entity.Coordinates}'polyline coordinates');$vertices=@();for($i=0;$i+1-lt$flat.Count;$i+=2){$vertices+=,@([double]$flat[$i],[double]$flat[$i+1])};$details.vertices=$vertices;$details.closed=[bool](Invoke-ComRetry{$Entity.Closed});$details.bulges=@();$details.widths=@();for($i=0;$i-lt$vertices.Count;$i++){[double]$sw=0;[double]$ew=0;$details.bulges+=[double](Invoke-ComRetry{$Entity.GetBulge($i)});Invoke-ComRetry{$Entity.GetWidth($i,[ref]$sw,[ref]$ew)}|Out-Null;$details.widths+=,@($sw,$ew)}}
  elseif($name-eq'AcDbText'){$details.position=Get-Point2(Invoke-NonNullCom{$Entity.InsertionPoint}'text insertion');$details.height=[double](Invoke-ComRetry{$Entity.Height});$details.rotation=[double](Invoke-ComRetry{$Entity.Rotation});$details.styleName=[string](Invoke-ComRetry{$Entity.StyleName});$details.text=[string](Invoke-ComRetry{$Entity.TextString})}
  else{$details.unsupported=$true}
  $transparency='';try{$transparency=[string](Invoke-ComRetry{$Entity.EntityTransparency})}catch{}
  $thickness=$null;try{$thickness=[double](Invoke-ComRetry{$Entity.Thickness})}catch{}
  return [ordered]@{objectName=$name;handle=[string](Invoke-ComRetry{$Entity.Handle});layer=[string](Invoke-ComRetry{$Entity.Layer});color=[int](Invoke-ComRetry{$Entity.Color});lineweight=[int](Invoke-ComRetry{$Entity.Lineweight});linetype=[string](Invoke-ComRetry{$Entity.Linetype});linetypeScale=[double](Invoke-ComRetry{$Entity.LinetypeScale});transparency=$transparency;thickness=$thickness;details=$details}
}
function Get-StateByHandle{param($Document,[string]$Handle);return Get-EntityState(Invoke-NonNullCom{$Document.HandleToObject($Handle)}"entity $Handle")}
function Get-LayerStates{param($Document,[string]$Layer);$result=@();$count=[int](Invoke-ComRetry{$Document.ModelSpace.Count});for($i=0;$i-lt$count;$i++){$entity=Invoke-ComRetry{$Document.ModelSpace.Item($i)};if([string](Invoke-ComRetry{$entity.Layer})-eq$Layer){$result+=Get-StateByHandle $Document ([string](Invoke-ComRetry{$entity.Handle}))}};return @($result|Sort-Object handle)}
function New-Line{param($Document,[string]$Layer,[double]$X1,[double]$Y1,[double]$X2,[double]$Y2);[double[]]$a=@($X1,$Y1,0);[double[]]$b=@($X2,$Y2,0);$entity=Invoke-ComRetry{$Document.ModelSpace.AddLine($a,$b)};Invoke-ComRetry{$entity.Layer=$Layer}|Out-Null;return $entity}
function New-Circle{param($Document,[string]$Layer,[double]$X,[double]$Y,[double]$Radius);[double[]]$center=@($X,$Y,0);$entity=Invoke-ComRetry{$Document.ModelSpace.AddCircle($center,$Radius)};Invoke-ComRetry{$entity.Layer=$Layer}|Out-Null;return $entity}
function New-Polyline{param($Document,[string]$Layer,[double[]]$Coordinates);$entity=Invoke-ComRetry{$Document.ModelSpace.AddLightWeightPolyline($Coordinates)};Invoke-ComRetry{$entity.Layer=$Layer}|Out-Null;return $entity}
function New-Text{param($Document,[string]$Layer,[string]$Text,[double]$X,[double]$Y,[double]$Height);[double[]]$point=@($X,$Y,0);$entity=Invoke-ComRetry{$Document.ModelSpace.AddText($Text,$point,$Height)};Invoke-ComRetry{$entity.Layer=$Layer}|Out-Null;return $entity}
function Set-SourceBasic{param($Entity);Invoke-ComRetry{$Entity.Layer='F030_SOURCE';$Entity.Color=1;$Entity.Linetype='HIDDEN';$Entity.LinetypeScale=2.5;$Entity.Lineweight=50;$Entity.Thickness=-3.25;$Entity.EntityTransparency='40'}|Out-Null}
function New-Selection{param($Entity,[double]$X,[double]$Y);$handle=[string](Invoke-ComRetry{$Entity.Handle});return "(list (handent `"$handle`") $(Format-Point $X $Y))"}
function Invoke-MatchProp{param($Document,$Source,[double]$SourceX,[double]$SourceY,$Targets);$marker=[Guid]::NewGuid().ToString('N');$sourceSelection=New-Selection $Source $SourceX $SourceY;$targetArgs=($Targets|ForEach-Object{New-Selection $_.entity $_.x $_.y})-join' ';$lisp="(progn (setvar `"USERS1`" `"`") (command `"_.MATCHPROP`" $sourceSelection $targetArgs `"`") (setvar `"USERS1`" `"$marker`") (princ))`n";Invoke-ComRetry{$Document.SendCommand($lisp)}|Out-Null;Wait-AcadMarker $Document $marker;Invoke-ComRetry{$Document.Regen(1)}|Out-Null}
function Test-Near{param([double]$A,[double]$B,[double]$Tolerance=0.000001);return [Math]::Abs($A-$B)-le$Tolerance}
function Test-Point{param($A,$B);return $A.Count-ge2-and(Test-Near $A[0] $B[0])-and(Test-Near $A[1] $B[1])}
function Test-StateEqual{param($A,$B);return ($A|ConvertTo-Json -Depth 12 -Compress)-eq($B|ConvertTo-Json -Depth 12 -Compress)}
function Test-BasicMatched{param($Source,$Target);return $Target.layer-eq$Source.layer-and$Target.color-eq$Source.color-and$Target.lineweight-eq$Source.lineweight-and$Target.linetype-eq$Source.linetype-and(Test-Near $Target.linetypeScale $Source.linetypeScale)-and$Target.transparency-eq$Source.transparency-and(Test-Near $Target.thickness $Source.thickness)}

$acad=$null;$scratch=$null;$result=$null;$owned=$false;$ownedIdentity=$null;$automationProcessId=0;$stage='bootstrap';$preExistingProcessIds=@(Get-Process -Name 'acad' -ErrorAction SilentlyContinue|ForEach-Object{[int]$_.Id})
try{
  $stage='create-owned-process';$acad=New-Object -ComObject AutoCAD.Application.24.3;[uint32]$acadPid=0;[void][F030WindowProcess]::GetWindowThreadProcessId([IntPtr][int64](Invoke-ComRetry{$acad.HWND}),[ref]$acadPid);$automationProcessId=[int]$acadPid;$owned=$automationProcessId-gt0-and$preExistingProcessIds-notcontains$automationProcessId;if(-not$owned){throw 'F-030 refuses to use a pre-existing AutoCAD process.'};$ownedIdentity=Write-OwnedPidSidecar $automationProcessId;$installedUpdateIdentity=Get-InstalledAutoCadUpdateIdentity;Invoke-ComRetry{$acad.Visible=$true}|Out-Null
  $stage='open-blank';$initialCount=[int](Invoke-ComRetry{$acad.Documents.Count});if($initialCount-gt0){$candidate=Invoke-ComRetry{$acad.ActiveDocument};if([string](Invoke-ComRetry{$candidate.FullName})-or-not[bool](Invoke-ComRetry{$candidate.Saved})-or[int](Invoke-ComRetry{$candidate.ModelSpace.Count})-ne0){throw 'F-030 refuses a non-blank initial document.'};$scratch=$candidate}else{$scratch=Invoke-ComRetry{$acad.Documents.Add()}};Invoke-ComRetry{$scratch.Activate()}|Out-Null;Wait-AcadIdle $scratch
  $stage='layers-and-linetype';foreach($name in @('F030_SOURCE','F030_TARGET','F030_LOCKED','F030_POLY','F030_TEXT')){Invoke-ComRetry{$scratch.Layers.Add($name)}|Out-Null};try{Invoke-ComRetry{$scratch.Linetypes.Load('HIDDEN','acad.lin')}|Out-Null}catch{if(-not(Invoke-ComRetry{$scratch.Linetypes.Item('HIDDEN')})){throw}}
  $stage='text-style';$fontPath='C:\Windows\Fonts\arial.ttf';if(-not(Test-Path -LiteralPath $fontPath)){throw "F-030 requires $fontPath"};$textStyle=Invoke-ComRetry{$scratch.TextStyles.Add('F030_STYLE')};Invoke-ComRetry{$textStyle.FontFile=$fontPath}|Out-Null

  $stage='basic-multiple';$source=New-Line $scratch 'F030_SOURCE' 0 0 100 0;Set-SourceBasic $source;$targetLine=New-Line $scratch 'F030_TARGET' 0 200 100 200;$targetCircle=New-Circle $scratch 'F030_TARGET' 200 200 25;$locked=New-Line $scratch 'F030_LOCKED' 0 400 100 400;$noop=New-Line $scratch 'F030_SOURCE' 0 450 100 450;Set-SourceBasic $noop;$handles=@(@($source,$targetLine,$targetCircle,$locked,$noop)|ForEach-Object{[string](Invoke-ComRetry{$_.Handle})});$basicSource=@($handles|ForEach-Object{Get-StateByHandle $scratch $_})
  Invoke-ComRetry{(Invoke-ComRetry{$scratch.Layers.Item('F030_LOCKED')}).Lock=$true}|Out-Null;Invoke-ComRetry{$scratch.StartUndoMark()}|Out-Null;try{Invoke-MatchProp $scratch $source 50 0 @(@{entity=$targetLine;x=50;y=200},@{entity=$targetCircle;x=225;y=200},@{entity=$locked;x=50;y=400},@{entity=$noop;x=50;y=450})}finally{Invoke-ComRetry{$scratch.EndUndoMark()}|Out-Null};$basicCommitted=@($handles|ForEach-Object{Get-StateByHandle $scratch $_});Invoke-ComRetry{$scratch.SendCommand("_.UNDO`n1`n")}|Out-Null;Start-Sleep -Milliseconds 750;Wait-AcadIdle $scratch;$basicUndone=@($handles|ForEach-Object{Get-StateByHandle $scratch $_});Invoke-ComRetry{$scratch.SendCommand("_.REDO`n")}|Out-Null;Start-Sleep -Milliseconds 750;Wait-AcadIdle $scratch;$basicRedone=@($handles|ForEach-Object{Get-StateByHandle $scratch $_})

  $stage='polyline-special';$polySource=New-Polyline $scratch 'F030_POLY' ([double[]]@(0,600,100,600));$polyTarget=New-Polyline $scratch 'F030_POLY' ([double[]]@(0,650,100,650));Invoke-ComRetry{$polySource.ConstantWidth=3;$polyTarget.SetWidth(0,1,2);$polyTarget.SetWidth(1,2,1);$polyTarget.SetBulge(0,0.5)}|Out-Null;$polySourceHandle=[string](Invoke-ComRetry{$polySource.Handle});$polyTargetHandle=[string](Invoke-ComRetry{$polyTarget.Handle});$polyBefore=Get-StateByHandle $scratch $polyTargetHandle;Invoke-MatchProp $scratch $polySource 50 600 @(@{entity=$polyTarget;x=50;y=650});$polyAfter=Get-StateByHandle $scratch $polyTargetHandle

  $stage='text-special';$textSource=New-Text $scratch 'F030_TEXT' 'SOURCE' 0 800 10;$textTarget=New-Text $scratch 'F030_TEXT' 'KEEP' 0 850 2;Invoke-ComRetry{$textSource.Rotation=0.5;$textSource.StyleName='F030_STYLE'}|Out-Null;$textSourceHandle=[string](Invoke-ComRetry{$textSource.Handle});$textTargetHandle=[string](Invoke-ComRetry{$textTarget.Handle});$textBefore=Get-StateByHandle $scratch $textTargetHandle;Invoke-MatchProp $scratch $textSource 10 800 @(@{entity=$textTarget;x=5;y=850});$textAfter=Get-StateByHandle $scratch $textTargetHandle

  $checks=[ordered]@{
    basicMultiple=(Test-BasicMatched $basicCommitted[0] $basicCommitted[1])-and(Test-BasicMatched $basicCommitted[0] $basicCommitted[2])
    targetIdentityGeometryPreserved=(Test-Point $basicCommitted[1].details.start @(0,200))-and(Test-Point $basicCommitted[1].details.end @(100,200))-and(Test-Point $basicCommitted[2].details.center @(200,200))-and(Test-Near $basicCommitted[2].details.radius 25)
    sourceUnchanged=Test-StateEqual $basicSource[0] $basicCommitted[0]
    lockedUnchanged=Test-StateEqual $basicSource[3] $basicCommitted[3]
    noOpUnchanged=Test-StateEqual $basicSource[4] $basicCommitted[4]
    atomicUndo=Test-StateEqual $basicSource $basicUndone
    atomicRedo=Test-StateEqual $basicCommitted $basicRedone
    polylineSpecial=(Test-Point $polyAfter.details.vertices[0] $polyBefore.details.vertices[0])-and(Test-Point $polyAfter.details.vertices[1] $polyBefore.details.vertices[1])-and(Test-Near $polyAfter.details.bulges[0] 0.5)-and@($polyAfter.details.widths|Where-Object{-not((Test-Near $_[0] 3)-and(Test-Near $_[1] 3))}).Count-eq0
    textSpecial=$textAfter.details.text-eq'KEEP'-and(Test-Point $textAfter.details.position $textBefore.details.position)-and(Test-Near $textAfter.details.height 10)-and(Test-Near $textAfter.details.rotation 0.5)-and$textAfter.details.styleName-eq'F030_STYLE'
  }
  $stage='save-dxf';Invoke-ComRetry{$scratch.Regen(1);$scratch.SaveAs($DxfOutputPath,65)} -TimeoutSeconds 90|Out-Null;Wait-AcadIdle $scratch;$finalStates=@();foreach($layer in @('F030_SOURCE','F030_TARGET','F030_LOCKED','F030_POLY','F030_TEXT')){$finalStates+=@(Get-LayerStates $scratch $layer)}
  $result=[ordered]@{schemaVersion=1;rowId='F-030';benchmark='AutoCAD 2024.1.2 / Windows / 2D Drafting & Annotation';engine='Autodesk AutoCAD 2024 desktop COM';engineVersion=[string](Invoke-ComRetry{$acad.Version});automationProcessId=$automationProcessId;automationProcessOwned=$owned;installedUpdateIdentity=$installedUpdateIdentity;automationProcessIdentity=[ordered]@{processId=$ownedIdentity.processId;executableName=$ownedIdentity.executableName;executableSha256=$ownedIdentity.executableSha256;fileVersion=$ownedIdentity.fileVersion;productVersion=$ownedIdentity.productVersion;startTimeSha256=$ownedIdentity.startTimeSha256};observations=[ordered]@{basic=[ordered]@{source=$basicSource;committed=$basicCommitted;undone=$basicUndone;redone=$basicRedone};polyline=[ordered]@{source=Get-StateByHandle $scratch $polySourceHandle;before=$polyBefore;after=$polyAfter};text=[ordered]@{source=Get-StateByHandle $scratch $textSourceHandle;before=$textBefore;after=$textAfter};unsupportedDependencies=@('dimension full special matrix','hatch origin/full special matrix','viewport full special matrix','multileader','table','center object','cross-drawing visible tab workflow','named plot style')};finalStates=$finalStates;checks=$checks;dxfOutputSha256=Get-FileSha256 $DxfOutputPath;cmdNamesAfter=[string](Invoke-ComRetry{$scratch.GetVariable('CMDNAMES')});userDocument=[ordered]@{isolatedOwnedProcess=$owned;blankRestored=$true};status=if(@($checks.Values|Where-Object{$_-ne$true}).Count-eq0){'PASS'}else{'FAIL'}}
}catch{throw "F-030 AutoCAD stage '$stage' failed at script line $($_.InvocationInfo.ScriptLineNumber): $($_.Exception.Message)"}
finally{if($acad-and-not$owned){try{[uint32]$finallyProcessId=0;[void][F030WindowProcess]::GetWindowThreadProcessId([IntPtr][int64](Invoke-ComRetry{$acad.HWND}),[ref]$finallyProcessId);if([int]$finallyProcessId-gt0-and$preExistingProcessIds-notcontains[int]$finallyProcessId){$automationProcessId=[int]$finallyProcessId;$ownedIdentity=Write-OwnedPidSidecar $automationProcessId;$owned=$true}}catch{}};if($scratch){try{Invoke-ComRetry{$scratch.Close($false)} -TimeoutSeconds 10|Out-Null}catch{}};if($owned-and$acad){try{Invoke-ComRetry{$acad.Quit()} -TimeoutSeconds 10|Out-Null}catch{}}}
if(-not$result){throw 'F-030 AutoCAD matrix produced no result.'};$result|ConvertTo-Json -Depth 16;if($result.status-ne'PASS'){exit 1}
