#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import DxfParser from "dxf-parser";
import { runOwnedDesktopMatrix, sha256 } from "./owned-desktop-matrix.mjs";

const root=process.cwd();const matrixScriptPath=resolve(root,"tools/autocad/f030-standard-matrix.ps1");const runnerPath=resolve(root,"tools/autocad/run-f030.mjs");const sharedRunnerPath=resolve(root,"tools/autocad/owned-desktop-matrix.mjs");const ownershipPath=resolve(root,"tools/autocad/process-ownership.mjs");const outputPath=resolve(root,process.argv[2]??"evidence/artifacts/F-030-autocad-readback.json");
const close=(a,b,t=1e-8)=>Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=t*Math.max(1,Math.abs(a),Math.abs(b));const point=(a,b)=>close(a?.x,b?.[0])&&close(a?.y,b?.[1]);
function rawEntityProperties(bytes){const lines=bytes.toString("utf8").split(/\r?\n/u);const records=new Map();let current=null;const flush=()=>{if(current?.handle)records.set(current.handle,current)};for(let index=0;index+1<lines.length;index+=2){const code=Number.parseInt(lines[index].trim(),10);const value=lines[index+1].trim();if(code===0){flush();current={type:value}}else if(current){if(code===5)current.handle=value;if(code===7)current.styleName=value;if(code===39)current.thickness=Number(value);if(code===43)current.constantWidth=Number(value);if(code===440)current.transparencyRaw=Number(value)}}flush();return records}
function transparencyLabel(raw){if(raw===undefined)return"ByLayer";const alpha=raw&255;return String(Math.round((1-alpha/255)*100))}
function summary(bytes){const parsed=new DxfParser().parseSync(bytes.toString("utf8"));const raw=rawEntityProperties(bytes);return{entityCount:parsed?.entities?.length??0,entities:(parsed?.entities??[]).map((e)=>{const properties=raw.get(e.handle)??{};return{handle:e.handle,layer:e.layer,type:e.type,colorIndex:e.colorIndex??256,lineweight:e.lineweight??-1,lineType:e.lineType??"ByLayer",lineTypeScale:e.lineTypeScale??1,thickness:properties.thickness??0,transparency:transparencyLabel(properties.transparencyRaw),constantWidth:properties.constantWidth,vertices:e.vertices?.map(({x,y,bulge,startWidth,endWidth})=>({x,y,bulge:bulge??0,startWidth:startWidth??0,endWidth:endWidth??0})),center:e.center?{x:e.center.x,y:e.center.y}:undefined,radius:e.radius,textPoint:e.startPoint?{x:e.startPoint.x,y:e.startPoint.y}:undefined,textHeight:e.textHeight,rotation:e.rotation,text:e.text,styleName:properties.styleName}})}};
function matches(d,n){const type={AcDbLine:"LINE",AcDbCircle:"CIRCLE",AcDbPolyline:"LWPOLYLINE",AcDbText:"TEXT"}[n?.objectName];if(!d||!type||d.type!==type||d.handle!==n.handle||d.layer!==n.layer||d.colorIndex!==n.color||d.lineweight!==n.lineweight||String(d.lineType).toLowerCase()!==String(n.linetype).toLowerCase()||!close(d.lineTypeScale,n.linetypeScale)||!close(d.thickness,n.thickness??0)||d.transparency!==n.transparency)return false;const x=n.details??{};if(type==="LINE")return d.vertices?.length===2&&point(d.vertices[0],x.start)&&point(d.vertices[1],x.end);if(type==="CIRCLE")return point(d.center,x.center)&&close(d.radius,x.radius);if(type==="LWPOLYLINE")return d.vertices?.length===x.vertices?.length&&d.vertices.every((v,i)=>point(v,x.vertices[i])&&close(v.bulge,x.bulges[i])&&(d.constantWidth===undefined?(close(v.startWidth,x.widths[i][0])&&close(v.endWidth,x.widths[i][1])):(close(d.constantWidth,x.widths[i][0])&&close(d.constantWidth,x.widths[i][1]))));if(type==="TEXT")return point(d.textPoint,x.position)&&close(d.textHeight,x.height)&&close((d.rotation??0)*Math.PI/180,x.rotation)&&d.text===x.text&&d.styleName===x.styleName;return false}
function validateDxf(bytes,matrix){const value=summary(bytes);const states=matrix?.finalStates??[];const byHandle=new Map(value.entities.map((entity)=>[entity.handle,entity]));return{...value,fullStateMatchesNative:states.length===9&&value.entityCount===9&&byHandle.size===9&&states.every((state)=>matches(byHandle.get(state.handle),state))}}
const matrix=await runOwnedDesktopMatrix({rowId:"F-030",matrixScriptPath,timeoutEnvironmentName:"F030_AUTOCAD_TIMEOUT_MS",validateDxf});
if(matrix.schemaVersion!==1||matrix.rowId!=="F-030"||!matrix.engineVersion?.startsWith("24.3")||matrix.automationProcessIdentity?.fileVersion!=="R24.3.152.0.0"||matrix.automationProcessIdentity?.productVersion!=="R24.3.152.0.0"||matrix.installedUpdateIdentity?.displayName!=="Autodesk AutoCAD 2024.1.2 Update"||matrix.installedUpdateIdentity?.displayVersion!=="24.3.152.0"||!matrix.automationProcessOwned||!matrix.automationProcessTerminated||!matrix.processSetRestored||matrix.status!=="PASS"||Object.values(matrix.checks??{}).some((value)=>value!==true)||matrix.cmdNamesAfter!==""||matrix.dxfReadback.sha256!==matrix.dxfOutputSha256||matrix.dxfReadback.fullStateMatchesNative!==true)throw new Error(`F-030 AutoCAD result mismatch: ${JSON.stringify(matrix)}`);
const report={...matrix,certificationAuthority:true,certificationScope:"basic + polyline + text subset only; unsupportedDependencies must be empty before F-030 score 1.00",workflow:"owned AutoCAD 2024.1.2 desktop MATCHPROP basic multiple/locked/no-op, polyline/text special and atomic Undo/Redo matrix + independently parsed DXF",matrixScriptSha256:sha256(await readFile(matrixScriptPath)),runnerSha256:sha256(await readFile(runnerPath)),sharedRunnerSha256:sha256(await readFile(sharedRunnerPath)),processOwnershipSha256:sha256(await readFile(ownershipPath)),observedAt:new Date().toISOString()};await mkdir(dirname(outputPath),{recursive:true});await writeFile(outputPath,`${JSON.stringify(report,null,2)}\n`,"utf8");console.log(`F-030 AutoCAD 2024.1.2 MATCHPROP supported-subset live matrix PASS; unresolved dependencies=${matrix.observations.unsupportedDependencies.length}.`);
